pipeline {
    agent any

    tools {
        maven 'Maven-3.9.2' // Configuré dans Jenkins : Manage Jenkins → Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ilalo20/Projet-DevOps-ImadLalouchi.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('hello-devops') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'hello-devops/target/*.jar'
            }
        }
    }

    post {
        success {
            withCredentials([string(credentialsId: 'slack-webhook', variable: 'SLACK_WEBHOOK')]) {
                sh '''
                curl -X POST \
                -H "Content-type: application/json" \
                --data '{"text":"✅ Jenkins Build SUCCESS"}' \
                "$SLACK_WEBHOOK"
                '''
            }
        }

        failure {
            withCredentials([string(credentialsId: 'slack-webhook', variable: 'SLACK_WEBHOOK')]) {
                sh '''
                curl -X POST \
                -H "Content-type: application/json" \
                --data '{"text":"❌ Jenkins Build FAILED"}' \
                "$SLACK_WEBHOOK"
                '''
            }
        }
    }

}