pipeline {
    agent any

    tools {
        maven 'Maven-3.9.2' // Configuré dans Jenkins : Manage Jenkins → Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ilalo20/Projet-DevOps-ImadLalouchi.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('hello-devops') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'hello-devops/target/*.jar'
            }
        }
    }

    post {
        success {
            slackSend(
                channel: '#jenkins',
                color: 'good',
                message: "✅ Build SUCCESS : ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                tokenCredentialId: 'slack-webhook' // ID du secret que tu as créé
            )
        }

        failure {
            slackSend(
                channel: '#jenkins',
                color: 'danger',
                message: "❌ Build FAILED : ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                tokenCredentialId: 'slack-webhook'
            )
        }
    }
}
