pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/TON_USER/Projet-DevOps-ImadLalouchi.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar'
            }
        }

        stage('Deploy') {
            when {
                success()
            }
            steps {
                echo "Déploiement réussi"
            }
        }
    }
}
